server:
  port: 8888
  
spring:
  cloud:    config:      server:        git:
          uri: https://github.com/fehferreira/microservice-repo-FlowerStore
          search-paths: fornecedor
          default-label: main